import type { TacticalFormation } from '../types';

export const FORMATIONS_PRESETS: TacticalFormation[] = [
  {
    id: '4-3-3',
    label: '4-3-3 (Clásico)',
    slots: [
      { id: 'arq', name: 'ARQ', category: 'arqueros', top: 86, left: 50 },
      { id: 'dfi', name: 'DFI', category: 'defensores', top: 68, left: 16 },
      { id: 'dfc1', name: 'DFC', category: 'defensores', top: 72, left: 38 },
      { id: 'dfc2', name: 'DFC', category: 'defensores', top: 72, left: 62 },
      { id: 'dfd', name: 'DFD', category: 'defensores', top: 68, left: 84 },
      { id: 'mc1', name: 'MC', category: 'mediocampistas', top: 48, left: 24 },
      { id: 'mcd', name: 'MCD', category: 'mediocampistas', top: 52, left: 50 },
      { id: 'mc2', name: 'MC', category: 'mediocampistas', top: 48, left: 76 },
      { id: 'ei', name: 'EI', category: 'delanteros', top: 22, left: 20 },
      { id: 'dc', name: 'DC', category: 'delanteros', top: 16, left: 50 },
      { id: 'ed', name: 'ED', category: 'delanteros', top: 22, left: 80 },
    ],
  },
  {
    id: '4-4-2',
    label: '4-4-2 (Tradicional)',
    slots: [
      { id: 'arq', name: 'ARQ', category: 'arqueros', top: 86, left: 50 },
      { id: 'dfi', name: 'DFI', category: 'defensores', top: 68, left: 16 },
      { id: 'dfc1', name: 'DFC', category: 'defensores', top: 72, left: 38 },
      { id: 'dfc2', name: 'DFC', category: 'defensores', top: 72, left: 62 },
      { id: 'dfd', name: 'DFD', category: 'defensores', top: 68, left: 84 },
      { id: 'mi', name: 'MI', category: 'mediocampistas', top: 46, left: 18 },
      { id: 'mc1', name: 'MC', category: 'mediocampistas', top: 50, left: 39 },
      { id: 'mc2', name: 'MC', category: 'mediocampistas', top: 50, left: 61 },
      { id: 'md', name: 'MD', category: 'mediocampistas', top: 46, left: 82 },
      { id: 'dc1', name: 'DC', category: 'delanteros', top: 18, left: 38 },
      { id: 'dc2', name: 'DC', category: 'delanteros', top: 18, left: 62 },
    ],
  },
  {
    id: '4-2-3-1',
    label: '4-2-3-1 (Ofensivo)',
    slots: [
      { id: 'arq', name: 'ARQ', category: 'arqueros', top: 86, left: 50 },
      { id: 'dfi', name: 'DFI', category: 'defensores', top: 70, left: 16 },
      { id: 'dfc1', name: 'DFC', category: 'defensores', top: 74, left: 38 },
      { id: 'dfc2', name: 'DFC', category: 'defensores', top: 74, left: 62 },
      { id: 'dfd', name: 'DFD', category: 'defensores', top: 70, left: 84 },
      { id: 'piv1', name: 'MCD', category: 'mediocampistas', top: 56, left: 36 },
      { id: 'piv2', name: 'MCD', category: 'mediocampistas', top: 56, left: 64 },
      { id: 'mi', name: 'MI', category: 'mediocampistas', top: 35, left: 20 },
      { id: 'mco', name: 'MCO', category: 'mediocampistas', top: 33, left: 50 },
      { id: 'md', name: 'MD', category: 'mediocampistas', top: 35, left: 80 },
      { id: 'dc', name: 'DC', category: 'delanteros', top: 15, left: 50 },
    ],
  },
  {
    id: '3-5-2',
    label: '3-5-2 (Carrileros)',
    slots: [
      { id: 'arq', name: 'ARQ', category: 'arqueros', top: 86, left: 50 },
      { id: 'dfc1', name: 'STO', category: 'defensores', top: 72, left: 24 },
      { id: 'dfc2', name: 'LIB', category: 'defensores', top: 74, left: 50 },
      { id: 'dfc3', name: 'STO', category: 'defensores', top: 72, left: 76 },
      { id: 'cai', name: 'CAI', category: 'mediocampistas', top: 48, left: 14 },
      { id: 'mc1', name: 'MC', category: 'mediocampistas', top: 52, left: 36 },
      { id: 'mcd', name: 'MCD', category: 'mediocampistas', top: 56, left: 50 },
      { id: 'mc2', name: 'MC', category: 'mediocampistas', top: 52, left: 64 },
      { id: 'cad', name: 'CAD', category: 'mediocampistas', top: 48, left: 86 },
      { id: 'dc1', name: 'DC', category: 'delanteros', top: 18, left: 38 },
      { id: 'dc2', name: 'DC', category: 'delanteros', top: 18, left: 62 },
    ],
  },
];
